import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { extname, join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as mdi from '@mdi/js';

const root = fileURLToPath(new URL('..', import.meta.url));
const check = process.argv.includes('--check');
const NAME = /\bmdi-[a-z0-9]+(?:-[a-z0-9]+)*\b/g;

const walk = (path) =>
  statSync(path).isDirectory() ? readdirSync(path).flatMap((entry) => walk(join(path, entry))) : [path];

const sources = (dir) =>
  existsSync(join(root, dir))
    ? walk(join(root, dir)).filter((file) => ['.vue', '.ts'].includes(extname(file)) && !file.endsWith('.generated.ts'))
    : [];

const isStoryFile = (file) => file.includes('.stories.') || file.includes(`${sep}mocks${sep}`);

const collect = (files) => {
  const names = new Set();
  for (const file of files) {
    for (const match of readFileSync(file, 'utf8').matchAll(NAME)) names.add(match[0]);
  }
  return [...names].toSorted();
};

const exportName = (name) =>
  `mdi${name
    .slice(4)
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')}`;

const version = JSON.parse(readFileSync(join(root, 'node_modules', '@mdi', 'js', 'package.json'), 'utf8')).version;

const render = (constant, names, description) => {
  const unknown = names.filter((name) => typeof mdi[exportName(name)] !== 'string');
  if (unknown.length > 0) throw new Error(`@mdi/js has no icon for: ${unknown.join(', ')}`);
  return [
    `// Generated by scripts/sync-icons.mjs from @mdi/js ${version} (Apache-2.0). Do not edit.`,
    `// ${description}`,
    `export const ${constant}: Readonly<Record<string, string>> = {`,
    ...names.map((name) => `  '${name}': '${mdi[exportName(name)]}',`),
    '};',
    '',
  ].join('\n');
};

const libFiles = sources('src').filter((file) => !isStoryFile(file));
const storyFiles = [...sources('src').filter(isStoryFile), ...sources('.storybook')];

const libNames = collect(libFiles);
const storyNames = collect(storyFiles).filter((name) => !libNames.includes(name));

const outputs = [
  {
    file: join(root, 'src', 'icons', 'icons.generated.ts'),
    content: render('MIXTAPE_ICON_PATHS', libNames, 'Ícones usados pelos componentes do pacote.'),
  },
  {
    file: join(root, '.storybook', 'story-icons.generated.ts'),
    content: render('STORY_ICON_PATHS', storyNames, 'Ícones usados só pelas stories e mocks (fora do pacote).'),
  },
];

let stale = false;
for (const { file, content } of outputs) {
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (check) {
    if (current !== content) {
      console.error(`${file} is out of date: run npm run sync:icons`);
      stale = true;
    }
  } else if (current !== content) {
    writeFileSync(file, content, 'utf8');
  }
}

if (stale) process.exitCode = 1;
else console.log(`icons ${check ? 'checked' : 'written'}: ${libNames.length} in the package, ${storyNames.length} only in stories (@mdi/js ${version})`);
